addSbtPlugin("com.github.sbt"            % "sbt-native-packager"    % "1.9.16")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"           % "0.4.2")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"           % "2.5.0")
addSbtPlugin("org.jmotor.sbt"            % "sbt-dependency-updates" % "1.2.7")
addSbtPlugin("au.com.onegeek"            % "sbt-dotenv"             % "2.1.233")
addSbtPlugin("org.wartremover"           % "sbt-wartremover"        % "3.1.4")
